service: visualisations-export-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 10
  region: eu-west-2
  endpointType: REGIONAL
  iam:
    role:
      managedPolicies:
        - "arn:aws:iam::186991146235:policy/AccessDataVizParameter"
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  index:
    handler: lambda.handler
    events:
      - http:
          path: /{library}/{options}/{hash}
          method: get
          request:
            parameters:
              paths:
                library: true
                options: true
                hash: true

package:
  patterns:
    - '!node_modules/@babel/**'
    - '!node_modules/@rollup/**'
    - '!node_modules/@types/**'
    - '!node_modules/core-js/**'
    - '!node_modules/d3*/**'
    - '!node_modules/express/**'
    - '!node_modules/serverless/**'
    - '!node_modules/terser/**'
    - '!src/**'
    - '!export-server/**'
    - '!package.json'
    - '!package-lock.json'
