service: visualisations-export-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 10

functions:
  index:
    handler: lambda.handler
    events:
      - httpApi:
          path: /
          method: post

package:
  patterns:
    - '!node_modules/@babel/**'
    - '!node_modules/@rollup/**'
    - '!node_modules/core-js/**'
    - '!node_modules/d3*/**'
    - '!node_modules/express/**'
    - '!node_modules/serverless/**'
    - '!src/**'
    - '!export-server/**'