name: Distribution Workflow

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout the project's sourcecode
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}

      # Set Node.js version
      - name: Request Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.6'
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      # set up git since we will later push to the repo
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "lee.jacobson1@nhs.net"

      - run: npm --no-git-tag-version version ${{ github.event.release.tag_name }}

      # build the project
      - run: npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # push the version changes to GitHub
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Store CDN distribution workflow artifacts
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cdn-dist
          path: |
            dist/
