name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  #
  # Build CDN Distribution from source
  #
  distribution:
    name: "Verify that the distribution builds correctly"
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      #
      # Step 1
      # Checkout the project's sourcecode
      #
      - name: Checkout
        uses: actions/checkout@v2

      #
      # Step 2
      # Set Node.js version
      #
      - name: Request Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.6'

      #
      # Step 3
      # Cache Management (CDN distribution)
      #
      - name: Get cache key helper values
        uses: actions/github-script@v3
        id: cache-key-helper
        with:
          result-encoding: string
          script: |
            return JSON.stringify({
              "year" : new Date().getFullYear(),
              "rotation" : new Date().getTimezoneOffset()
            })
      - name: Setup cache (Node.js packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-nhsd-viz-distribution-${{ env.YEAR }}-${{ env.ROTATION }}
          restore-keys: |
            ${{ runner.os }}-nhsd-viz-distribution-${{ env.YEAR }}-
            ${{ runner.os }}-nhsd-viz-distribution-

      #
      # Step 4
      #
      - name: Initialise NPM
        run: npm ci

      #
      # Step 5
      #
      - name: Build Distribution
        run: npm run build
